# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "clap"
        versions: ["4.x"]
