[package]
name = "dotfiles"
version = "0.5.0"
edition = "2021"

[[bin]]
name = "dotf"
path = "src/bin/dotf.rs"

[profile.release]
strip = true

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["cargo"] }
data-encoding = "2.3"
glob = "0.3.0"
home = "0.5.3"
log = "0.4"
env_logger = "0.8"
ring = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
rand = "0.8.4"
