[package]
name = "dotfiles"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dotfiles"
path = "src/bin/dotfiles.rs"

[dependencies]
anyhow = "1.0"
clap = "3.0"
data-encoding = "2.3"
home = "0.5.3"
log = "0.4"
env_logger = "0.8"
ring = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
rand = "0.8.4"
